### PR TITLE
Nette 3 support

### PR DESCRIPTION
**Pull request by xsuchy09**
Not the best way but looks functional ...

### CODE REVIEW

**Comment by akadlec** [comment]
again not correct. take a look here: https://github.com/ipublikuj/flysystem/blob/master/composer.json

**Comment by xsuchy09** [comment]
Can you be specific? I am just trying to make new version valid for Nette 3 as fast as possible at all, nothing special was done from me ...

**Comment by akadlec** [comment]
you can not strictly set nette 3 as required

**Comment by xsuchy09** [comment]
I set it to ^3.0, so Nette >=3.0 and <4.0 ... and I tagged it as new major version. But you think that it is better idea to set ^3.0|^2.4 and don't have one version for Nette 3 and one for older one (Nette 2.4)?

**Comment by akadlec** [comment]
if code changes allow to use it on old version, then old version should be allowed

**Comment by xsuchy09** [comment]
If you think that it is good idea I can test and change it later.

But I think that major and separate version is better idea here as others extensions are doing this in the same way ... I think that you thought that ^3.0 is strict Nette 3 which is not ... so let me know ... thanks.

**Comment by akadlec** [comment]
Closing, done other way.

**Pull request closed without merging**
